AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation StackSet for S3 Bucket'
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to create.
    Default: my-s3-bucket
  Region:
    Type: String
    Description: The region in which to create the S3 bucket.
    Default: ap-southeast-2
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "${BucketName}-${AWS::AccountId}"
